# Generated by Django 5.1.6 on 2025-02-21 04:09

import app.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("business", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                (
                    "login",
                    models.CharField(
                        max_length=100, validators=[app.validators.profanity_validator]
                    ),
                ),
                ("age", models.PositiveIntegerField()),
                (
                    "location",
                    models.CharField(
                        max_length=500, validators=[app.validators.profanity_validator]
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("MALE", "Male"), ("FEMALE", "Female")], max_length=6
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Click",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_id", models.UUIDField(db_index=True)),
                ("cost", models.FloatField()),
                ("advertiser_id", models.UUIDField(db_index=True)),
                ("day", models.BigIntegerField(db_index=True)),
                (
                    "advertisement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="click_set",
                        to="business.campaign",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["advertisement"], name="client_clic_adverti_ed0edd_idx"
                    ),
                    models.Index(
                        fields=["advertiser_id"], name="client_clic_adverti_13c970_idx"
                    ),
                    models.Index(fields=["day"], name="client_clic_day_6631c5_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Impression",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_id", models.UUIDField(db_index=True)),
                ("cost", models.FloatField()),
                ("advertiser_id", models.UUIDField(db_index=True)),
                ("day", models.BigIntegerField(db_index=True)),
                (
                    "advertisement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="impression_set",
                        to="business.campaign",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["advertisement"], name="client_impr_adverti_49d476_idx"
                    ),
                    models.Index(
                        fields=["advertiser_id"], name="client_impr_adverti_12570b_idx"
                    ),
                    models.Index(fields=["day"], name="client_impr_day_19d8f7_idx"),
                ],
            },
        ),
    ]
