# Generated by Django 5.1.6 on 2025-02-22 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_initial'),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='click',
            name='client_clic_adverti_13c970_idx',
        ),
        migrations.RemoveIndex(
            model_name='impression',
            name='client_impr_adverti_12570b_idx',
        ),
        migrations.AlterUniqueTogether(
            name='impression',
            unique_together={('client_id', 'advertisement')},
        ),
        migrations.AddIndex(
            model_name='click',
            index=models.Index(fields=['client_id'], name='client_clic_client__ea720b_idx'),
        ),
        migrations.AddIndex(
            model_name='impression',
            index=models.Index(fields=['client_id'], name='client_impr_client__b80b68_idx'),
        ),
    ]
