# Generated by Django 5.1.6 on 2025-02-21 04:09

import app.validators
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Advertiser",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        max_length=100, validators=[app.validators.profanity_validator]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("impressions_limit", models.PositiveIntegerField()),
                ("clicks_limit", models.PositiveIntegerField()),
                (
                    "cost_per_impression",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "cost_per_click",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "ad_title",
                    models.CharField(
                        max_length=100, validators=[app.validators.profanity_validator]
                    ),
                ),
                (
                    "ad_text",
                    models.CharField(
                        max_length=500, validators=[app.validators.profanity_validator]
                    ),
                ),
                ("start_date", models.PositiveIntegerField()),
                ("end_date", models.PositiveIntegerField()),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
                (
                    "targeted_gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MALE", "Male"),
                            ("FEMALE", "Female"),
                            ("ALL", "All"),
                        ],
                        max_length=6,
                        null=True,
                    ),
                ),
                (
                    "targeted_age_from",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("targeted_age_to", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "targeted_location",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        validators=[app.validators.profanity_validator],
                    ),
                ),
                ("erid", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "advertiser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaigns",
                        to="business.advertiser",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Score",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.IntegerField()),
                (
                    "advertiser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="business.advertiser",
                    ),
                ),
            ],
        ),
    ]
