# Generated by Django 5.1.6 on 2025-02-22 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='clicks_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='impressions_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['impressions_count'], name='business_ca_impress_dba35f_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['clicks_count'], name='business_ca_clicks__99cbf1_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['impressions_limit'], name='business_ca_impress_b66d68_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['clicks_limit'], name='business_ca_clicks__4bab2e_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['start_date'], name='business_ca_start_d_b96434_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['end_date'], name='business_ca_end_dat_a33374_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['targeted_gender'], name='business_ca_targete_bbe0c2_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['targeted_age_from'], name='business_ca_targete_a2dfd9_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['targeted_age_to'], name='business_ca_targete_bef6d0_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['targeted_location'], name='business_ca_targete_ee6020_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['erid'], name='business_ca_erid_f650ca_idx'),
        ),
    ]
